name: Docker Publish
description: Build & Publish Docker image
inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 20.18.1
  registry:
    description: The Docker registry to use
    required: true
    default: ghcr.io
  imageName:
    description: Docker image name
    required: true
    default: ${{ github.repository }}
  githubToken:
    description: GitHub token
    required: true
  tagName:
    description: Optional tag name for image
    required: false

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.githubToken }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ inputs.registry }}/${{ inputs.imageName }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.imageName }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
