name: Docker Publish
description: Build & Publish Docker image
inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 24
  registry:
    description: The Docker registry to use
    required: true
    default: ghcr.io
  imageName:
    description: Docker image name
    required: true
    default: ${{ github.repository }}
  githubToken:
    description: GitHub token
    required: true
  push:
    description: Push image to registry
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.githubToken }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.imageName }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ inputs.push }}
        sbom: true
        github-token: ${{ inputs.githubToken }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ github.workspace }}/docker/Dockerfile

    - name: Generate artifact attestation
      if: inputs.push != 'false'
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.imageName }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: ${{ inputs.push }}
