name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: npm run codegen
      - run: npm run check
      - name: Lint
        shell: bash
        run: npm run lint:fix && git add packages/*/src && git diff-index --cached HEAD --exit-code packages/*/src

  test:
    name: Build Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - uses: ./.github/actions/dockerPublish
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          push: false
