name: Release
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: npm run changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: ./.github/actions/buildAction

      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: ./.github/actions/dockerPublish
