name: Tagged Release
on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  release:
    name: Release Tagged version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Publish
        uses: ./.github/actions/dockerPublish
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
